'use strict';
import HTMLElementFactoryCollection from '../HTMLElementFactoryCollection.js';

import createHTMLIoTAisleElement from './HTMLIoTAisleElement.js';
import createHTMLIoTShelvingUnitElement from './HTMLIoTShelvingUnitElement.js';
import createHTMLIoTButtonElement from './HTMLIoTButtonElement.js';
import createHTMLIoTVideoElement from './HTMLIoTVideoElement.js';
import createHTMLIoTAudioElement from './HTMLIoTAudioElement.js';
import createHTMLIoTPodiumElement from './HTMLIoTPodiumElement.js';
import createHTMLIoTTileElement from './HTMLIoTTileElement.js';
import createHTMLIoTItemElement from './HTMLIoTItemElement.js';
import createHTMLIoTRoomElement from './HTMLIoTRoomElement.js';
import createHTMLIoTBasketElement from './HTMLIoTBasketElement.js';
import createHTMLIoTShelfElement from './HTMLIoTShelfElement.js';
import createHTMLIoTCustomerElement from './HTMLIoTCustomerElement.js';
import createHTMLIoTGondolaElement from './HTMLIoTGondolaElement.js';
import createHTMLIoTCompartmentElement from './HTMLIoTCompartmentElement.js';
import createHTMLIoTColumnElement from './HTMLIoTColumnElement.js';
import createHTMLIoTLineElement from './HTMLIoTLineElement.js';
import createHTMLIoTCubbyElement from './HTMLIoTCubbyElement.js';
import createHTMLIoTEndcapElement from './HTMLIoTEndcapElement.js';
import createHTMLIoTDisplayUnitElement from './HTMLIoTDisplayUnitElement.js';

const elementFactoryCollection = new HTMLElementFactoryCollection();
export default elementFactoryCollection;

elementFactoryCollection.add('iot-aisle', createHTMLIoTAisleElement);
elementFactoryCollection.add('iot-shelving-unit', createHTMLIoTShelvingUnitElement);
elementFactoryCollection.add('iot-button', createHTMLIoTButtonElement);
elementFactoryCollection.add('iot-video', createHTMLIoTVideoElement);
elementFactoryCollection.add('iot-audio', createHTMLIoTAudioElement);
elementFactoryCollection.add('iot-podium', createHTMLIoTPodiumElement);
elementFactoryCollection.add('iot-tile', createHTMLIoTTileElement);
elementFactoryCollection.add('iot-item', createHTMLIoTItemElement);
elementFactoryCollection.add('iot-room', createHTMLIoTRoomElement);
elementFactoryCollection.add('iot-basket', createHTMLIoTBasketElement);
elementFactoryCollection.add('iot-shelf', createHTMLIoTShelfElement);
elementFactoryCollection.add('iot-customer', createHTMLIoTCustomerElement);
elementFactoryCollection.add('iot-gondola', createHTMLIoTGondolaElement);
elementFactoryCollection.add('iot-compartment', createHTMLIoTCompartmentElement);
elementFactoryCollection.add('iot-column', createHTMLIoTColumnElement);
elementFactoryCollection.add('iot-line', createHTMLIoTLineElement);
elementFactoryCollection.add('iot-cubby', createHTMLIoTCubbyElement);
elementFactoryCollection.add('iot-endcap', createHTMLIoTEndcapElement);
elementFactoryCollection.add('iot-display-unit', createHTMLIoTDisplayUnitElement);
